$axure.loadCurrentPage({
  "url":"cooperation.html",
  "generationDate":new Date(1395490956499.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bbee44f1247d4441a53ec0ad74332383",
    "type":"Axure:Page",
    "name":"Cooperation",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"14456fa33933422598b3252264028609",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"300638b8603e48f5bbcc98a6c99f05fc"},
{
          "id":"d6105238001b4003b944ec9669093e87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":228},
            "size":{
              "width":499,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7d0384ea34b47feaafb8f472d0d6b38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":228},
                "size":{
                  "width":499,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u22.jpg"}},
{
          "id":"de10840c691340fb8c5754595f8f1ed1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "paddingTop":"0",
            "paddingBottom":"0",
            "location":{
              "x":530,
              "y":209},
            "size":{
              "width":93,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba7f646d3f2f4bc98b462a1d31c22b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "paddingTop":"0",
                "paddingBottom":"0",
                "location":{
                  "x":530,
                  "y":209},
                "size":{
                  "width":93,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u24.png"}},
{
          "id":"6af01382112844918def0ef2e3420ad3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":1121},
            "size":{
              "width":29,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ae53038abb443f1add9db4196dc61c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":1121},
                "size":{
                  "width":29,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://www.facebook.com/dycargo in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.facebook.com/dycargo",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/about_us/u29.png"}},
{
          "id":"a59012f1ca7d4d7080f78e85aebdb269",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":364},
            "size":{
              "width":167,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfd4d1ac8fe448d990380c0a5c72b445",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":364},
                "size":{
                  "width":167,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u28.jpg"}},
{
          "id":"3fd49a2fb21f41299572ae516e50acfa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":364},
            "size":{
              "width":167,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed204a6ec4574b25952a0c0aedaa2347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":364},
                "size":{
                  "width":167,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u30.jpg"}},
{
          "id":"f2aadb4259d64f13a7b2c9cb349c565e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":841,
              "y":364},
            "size":{
              "width":167,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a815236563549119f85de8eae2aeafa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":841,
                  "y":364},
                "size":{
                  "width":167,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u32.jpg"}},
{
          "id":"0d4df5384da148faa80ac80d5c6f54f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":434},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b367f0ee5bc2437c9c6bccb107cdfb42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":434},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u34.jpg"}},
{
          "id":"5c50c10abb5e41d2a76ca6b7a7e60225",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":504},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"546864a89a4d4cddb280277baeceb248",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":504},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u36.jpg"}},
{
          "id":"d4518951a0544096899bfd5fff662cb1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":434},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6865f17c228c49acb2279ba6ee08c9ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":434},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u38.jpg"}},
{
          "id":"0b56b673b1fb4bd383fc39d4b93377d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":838,
              "y":434},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e695f298d25441183458512ddbb8260",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":838,
                  "y":434},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u40.jpg"}},
{
          "id":"46296074c41c45d8a26833edcbbacfae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":504},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e19d0cccf19f4be688b2845e8da3f765",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":504},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u42.jpg"}},
{
          "id":"0656300efa56409fb86a54b8dc5e97d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":838,
              "y":504},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9035d0596fa494f940b14a8f1181ca4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":838,
                  "y":504},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u44.jpg"}},
{
          "id":"af079c7e45b742f0ab18aedabe876a54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":584},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c3c5db44a074d2393c1c73fe1221c28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":584},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u46.jpg"}},
{
          "id":"fdd135029f2a4c9eb2af8b952373e242",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":584},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b276f4af4744cea9728681c1a281073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":584},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u48.jpg"}},
{
          "id":"79071523d8e04f429e0ebcf2a68f8cb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":838,
              "y":584},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b79f2d055c7464e94390f621809b4f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":838,
                  "y":584},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u50.jpg"}},
{
          "id":"c3fc67885d2344d796e3c257139ce107",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":664},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac17e6294fe141f9a942e6e857fd79b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":664},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u52.jpg"}},
{
          "id":"6ec3cb4ec642489f9451c2cd687926f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":664},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54fe6b4cb47a4d59ad00cbe3334d610d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":664},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u54.jpg"}},
{
          "id":"84e9689b7e3e4fba9de1654f8782ae3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":838,
              "y":664},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f976bf1b22164a1b93980c27ceca6bbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":838,
                  "y":664},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u56.jpg"}},
{
          "id":"9a6bd70d4e5e4c6f99dd0ad6b64e5ef2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":744},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"427688c2064b49758674877779ca4004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":744},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u58.jpg"}},
{
          "id":"03aefa303e18414dbf20ab95ea2beea0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":744},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fd9685162c64a26a497f37ae2cc676e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":744},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u60.jpg"}},
{
          "id":"54b69c9514474870a6fbca56a678a791",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":838,
              "y":744},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a67b4501076438f81f8a36a458db777",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":838,
                  "y":744},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u62.jpg"}},
{
          "id":"e4a93b5691234691bc71f8ccf7c2b4f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":824},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"142988db169143168971ae8dc5bbaeff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":824},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u64.jpg"}},
{
          "id":"1a3682e0b52b45cc921ecbbf7d5e2e57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":824},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd30b47dab1a478cb5d1093f6a32fd03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":824},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u66.jpg"}},
{
          "id":"ce374addb85447fe82acf5f924018617",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":838,
              "y":824},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cabfe53a6aa4593a6abc163df87fdd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":838,
                  "y":824},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u68.jpg"}},
{
          "id":"fc2d7a0436194fd7a3c5a592e140530f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":904},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6608ef93fd4943a99f572d595e23c530",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":904},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u70.jpg"}},
{
          "id":"c31e2a75329b4ae883d38580c7eda473",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":667,
              "y":904},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d3eee7e9be94476b0b1340e0a8227a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":667,
                  "y":904},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u72.jpg"}},
{
          "id":"f2d1b1754cd5448699995ced6684efac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":837,
              "y":904},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0e0cf85a034c519dcc4ee0a25b9de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":837,
                  "y":904},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u74.jpg"}},
{
          "id":"e8ae707f73d4492c95bc08f365b89000",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":498,
              "y":984},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b18dccb2cbd44f2cb1fdacc059f14559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":984},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u76.jpg"}},
{
          "id":"900eadae064349538630d244fa1abde5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":668,
              "y":984},
            "size":{
              "width":170,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"011fbea383794c4fb75867e310771ae2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":668,
                  "y":984},
                "size":{
                  "width":170,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cooperation/u78.jpg"}},
{
          "id":"8e9b04ad149741af97a77e5e4189d13d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1232},
            "size":{
              "width":1410,
              "height":40}},
          "adaptiveStyles":{
},
          "masterId":"48d86b2629bf42b6b5fe5ea73f1894df"}]}},
  "masters":{
    "300638b8603e48f5bbcc98a6c99f05fc":{
      "packageId":"300638b8603e48f5bbcc98a6c99f05fc",
      "type":"Axure:Master",
      "name":"a",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"6440bb14359e49cba4434be153f3526c",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "size":{
                "width":1100,
                "height":830}},
            "adaptiveStyles":{
},
            "masterId":"afe0e176cbfc496eb9952444a4aaf9e9"}]}},
    "afe0e176cbfc496eb9952444a4aaf9e9":{
      "packageId":"afe0e176cbfc496eb9952444a4aaf9e9",
      "type":"Axure:Master",
      "name":"New Master 5",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0c30b16567da45199bf81b2458faa8d6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":0},
              "size":{
                "width":300,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4496c6034dce461e8cad8352dd0d3f5f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":0},
                  "size":{
                    "width":300,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u2.png"}},
{
            "id":"e4af84012d284df8b202f3355adfb5c8",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":120},
              "size":{
                "width":1000,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0664a18133c1458ca23a821d36e3d42f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":120},
                  "size":{
                    "width":1000,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u4.jpg"}},
{
            "id":"f929c8603d5849f9a923c63bd7f1ca0b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":259,
                "y":396},
              "size":{
                "width":100,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eb329fd4207c47f09ec88a13cfbdb5ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":259,
                    "y":396},
                  "size":{
                    "width":100,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About us in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about_us.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/index/u6.png"}},
{
            "id":"3c2f59e45b6844f98290e6acf16f8be3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":259,
                "y":496},
              "size":{
                "width":120,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"74b4d3e820ad494a84e2867d40693f5a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":259,
                    "y":496},
                  "size":{
                    "width":120,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Tailored services in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"tailored_services.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/index/u8.png"}},
{
            "id":"cc54c5eef38b43efad182b965a196621",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":259,
                "y":596},
              "size":{
                "width":100,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7fe37bd2d784eff8acba786dc764202",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":259,
                    "y":596},
                  "size":{
                    "width":100,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Yiwu roadmap in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"yiwu_roadmap.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/index/u10.png"}},
{
            "id":"d4e166e8ce8c4003b569838d672e40e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":259,
                "y":800},
              "size":{
                "width":100,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ee2483192094220ac057d16f61a4390",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":259,
                    "y":800},
                  "size":{
                    "width":100,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contact us in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contact_us.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/index/u12.png"}},
{
            "id":"70de00b9ae1f4483bdb0084cdd98238e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":259,
                "y":696},
              "size":{
                "width":100,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"08cea061c3ef4bb982b85fdbe349a577",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":259,
                    "y":696},
                  "size":{
                    "width":100,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Cooperation in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"cooperation.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/index/u14.png"}},
{
            "id":"ea240947a7f34243878463e566b77554",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":259,
                "y":296},
              "size":{
                "width":100,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"171b704af5094148977e2ede354ce673",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":259,
                    "y":296},
                  "size":{
                    "width":100,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open index in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"index.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/index/u16.png"}},
{
            "id":"4082cfdbe8224238af35fd49e95bebc6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":500,
                "y":0},
              "size":{
                "width":800,
                "height":90}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"77de21c6b2b548369a0817ab3892447e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":500,
                    "y":0},
                  "size":{
                    "width":800,
                    "height":90}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u18.png"}},
{
            "id":"77c22a3e2f7748efa173688b31cf034d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF1E1E1E,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":210,
                "y":90},
              "size":{
                "width":990,
                "height":1},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b58c6cc77c0347e38eae0dc3ffb00b84",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF1E1E1E,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":210,
                    "y":90},
                  "size":{
                    "width":990,
                    "height":1},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u20.png"}}]}},
    "48d86b2629bf42b6b5fe5ea73f1894df":{
      "packageId":"48d86b2629bf42b6b5fe5ea73f1894df",
      "type":"Axure:Master",
      "name":"b",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f2bbaa828a0346da948bd41fa93fdf94",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "size":{
                "width":1420,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/index/u27_line.png"}},
{
            "id":"99b5c8b1cdd14461b0f950bc09b1ab10",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":10},
              "size":{
                "width":1300,
                "height":30}},
            "adaptiveStyles":{
},
            "masterId":"b9eada5165d243e3a88849de7d631760"}]}},
    "b9eada5165d243e3a88849de7d631760":{
      "packageId":"b9eada5165d243e3a88849de7d631760",
      "type":"Axure:Master",
      "name":"New Master 2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7f8c2baef61e46d2bdc961b715fd5d31",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1410,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"81da1ed11dd642eebd65ea78b814a0d1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1410,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u29.png"}}]}}},
  "objectPaths":{
    "14456fa33933422598b3252264028609":{
      "scriptId":"u0",
      "6440bb14359e49cba4434be153f3526c":{
        "scriptId":"u1",
        "0c30b16567da45199bf81b2458faa8d6":{
          "scriptId":"u2"},
        "4496c6034dce461e8cad8352dd0d3f5f":{
          "scriptId":"u3"},
        "e4af84012d284df8b202f3355adfb5c8":{
          "scriptId":"u4"},
        "0664a18133c1458ca23a821d36e3d42f":{
          "scriptId":"u5"},
        "f929c8603d5849f9a923c63bd7f1ca0b":{
          "scriptId":"u6"},
        "eb329fd4207c47f09ec88a13cfbdb5ea":{
          "scriptId":"u7"},
        "3c2f59e45b6844f98290e6acf16f8be3":{
          "scriptId":"u8"},
        "74b4d3e820ad494a84e2867d40693f5a":{
          "scriptId":"u9"},
        "cc54c5eef38b43efad182b965a196621":{
          "scriptId":"u10"},
        "e7fe37bd2d784eff8acba786dc764202":{
          "scriptId":"u11"},
        "d4e166e8ce8c4003b569838d672e40e2":{
          "scriptId":"u12"},
        "7ee2483192094220ac057d16f61a4390":{
          "scriptId":"u13"},
        "70de00b9ae1f4483bdb0084cdd98238e":{
          "scriptId":"u14"},
        "08cea061c3ef4bb982b85fdbe349a577":{
          "scriptId":"u15"},
        "ea240947a7f34243878463e566b77554":{
          "scriptId":"u16"},
        "171b704af5094148977e2ede354ce673":{
          "scriptId":"u17"},
        "4082cfdbe8224238af35fd49e95bebc6":{
          "scriptId":"u18"},
        "77de21c6b2b548369a0817ab3892447e":{
          "scriptId":"u19"},
        "77c22a3e2f7748efa173688b31cf034d":{
          "scriptId":"u20"},
        "b58c6cc77c0347e38eae0dc3ffb00b84":{
          "scriptId":"u21"}}},
    "d6105238001b4003b944ec9669093e87":{
      "scriptId":"u22"},
    "c7d0384ea34b47feaafb8f472d0d6b38":{
      "scriptId":"u23"},
    "de10840c691340fb8c5754595f8f1ed1":{
      "scriptId":"u24"},
    "ba7f646d3f2f4bc98b462a1d31c22b62":{
      "scriptId":"u25"},
    "6af01382112844918def0ef2e3420ad3":{
      "scriptId":"u26"},
    "9ae53038abb443f1add9db4196dc61c7":{
      "scriptId":"u27"},
    "a59012f1ca7d4d7080f78e85aebdb269":{
      "scriptId":"u28"},
    "bfd4d1ac8fe448d990380c0a5c72b445":{
      "scriptId":"u29"},
    "3fd49a2fb21f41299572ae516e50acfa":{
      "scriptId":"u30"},
    "ed204a6ec4574b25952a0c0aedaa2347":{
      "scriptId":"u31"},
    "f2aadb4259d64f13a7b2c9cb349c565e":{
      "scriptId":"u32"},
    "9a815236563549119f85de8eae2aeafa":{
      "scriptId":"u33"},
    "0d4df5384da148faa80ac80d5c6f54f5":{
      "scriptId":"u34"},
    "b367f0ee5bc2437c9c6bccb107cdfb42":{
      "scriptId":"u35"},
    "5c50c10abb5e41d2a76ca6b7a7e60225":{
      "scriptId":"u36"},
    "546864a89a4d4cddb280277baeceb248":{
      "scriptId":"u37"},
    "d4518951a0544096899bfd5fff662cb1":{
      "scriptId":"u38"},
    "6865f17c228c49acb2279ba6ee08c9ca":{
      "scriptId":"u39"},
    "0b56b673b1fb4bd383fc39d4b93377d4":{
      "scriptId":"u40"},
    "2e695f298d25441183458512ddbb8260":{
      "scriptId":"u41"},
    "46296074c41c45d8a26833edcbbacfae":{
      "scriptId":"u42"},
    "e19d0cccf19f4be688b2845e8da3f765":{
      "scriptId":"u43"},
    "0656300efa56409fb86a54b8dc5e97d9":{
      "scriptId":"u44"},
    "d9035d0596fa494f940b14a8f1181ca4":{
      "scriptId":"u45"},
    "af079c7e45b742f0ab18aedabe876a54":{
      "scriptId":"u46"},
    "2c3c5db44a074d2393c1c73fe1221c28":{
      "scriptId":"u47"},
    "fdd135029f2a4c9eb2af8b952373e242":{
      "scriptId":"u48"},
    "4b276f4af4744cea9728681c1a281073":{
      "scriptId":"u49"},
    "79071523d8e04f429e0ebcf2a68f8cb3":{
      "scriptId":"u50"},
    "5b79f2d055c7464e94390f621809b4f2":{
      "scriptId":"u51"},
    "c3fc67885d2344d796e3c257139ce107":{
      "scriptId":"u52"},
    "ac17e6294fe141f9a942e6e857fd79b4":{
      "scriptId":"u53"},
    "6ec3cb4ec642489f9451c2cd687926f7":{
      "scriptId":"u54"},
    "54fe6b4cb47a4d59ad00cbe3334d610d":{
      "scriptId":"u55"},
    "84e9689b7e3e4fba9de1654f8782ae3c":{
      "scriptId":"u56"},
    "f976bf1b22164a1b93980c27ceca6bbb":{
      "scriptId":"u57"},
    "9a6bd70d4e5e4c6f99dd0ad6b64e5ef2":{
      "scriptId":"u58"},
    "427688c2064b49758674877779ca4004":{
      "scriptId":"u59"},
    "03aefa303e18414dbf20ab95ea2beea0":{
      "scriptId":"u60"},
    "6fd9685162c64a26a497f37ae2cc676e":{
      "scriptId":"u61"},
    "54b69c9514474870a6fbca56a678a791":{
      "scriptId":"u62"},
    "2a67b4501076438f81f8a36a458db777":{
      "scriptId":"u63"},
    "e4a93b5691234691bc71f8ccf7c2b4f6":{
      "scriptId":"u64"},
    "142988db169143168971ae8dc5bbaeff":{
      "scriptId":"u65"},
    "1a3682e0b52b45cc921ecbbf7d5e2e57":{
      "scriptId":"u66"},
    "cd30b47dab1a478cb5d1093f6a32fd03":{
      "scriptId":"u67"},
    "ce374addb85447fe82acf5f924018617":{
      "scriptId":"u68"},
    "6cabfe53a6aa4593a6abc163df87fdd0":{
      "scriptId":"u69"},
    "fc2d7a0436194fd7a3c5a592e140530f":{
      "scriptId":"u70"},
    "6608ef93fd4943a99f572d595e23c530":{
      "scriptId":"u71"},
    "c31e2a75329b4ae883d38580c7eda473":{
      "scriptId":"u72"},
    "4d3eee7e9be94476b0b1340e0a8227a4":{
      "scriptId":"u73"},
    "f2d1b1754cd5448699995ced6684efac":{
      "scriptId":"u74"},
    "7a0e0cf85a034c519dcc4ee0a25b9de4":{
      "scriptId":"u75"},
    "e8ae707f73d4492c95bc08f365b89000":{
      "scriptId":"u76"},
    "b18dccb2cbd44f2cb1fdacc059f14559":{
      "scriptId":"u77"},
    "900eadae064349538630d244fa1abde5":{
      "scriptId":"u78"},
    "011fbea383794c4fb75867e310771ae2":{
      "scriptId":"u79"},
    "8e9b04ad149741af97a77e5e4189d13d":{
      "scriptId":"u80",
      "f2bbaa828a0346da948bd41fa93fdf94":{
        "scriptId":"u81"},
      "99b5c8b1cdd14461b0f950bc09b1ab10":{
        "scriptId":"u82",
        "7f8c2baef61e46d2bdc961b715fd5d31":{
          "scriptId":"u83"},
        "81da1ed11dd642eebd65ea78b814a0d1":{
          "scriptId":"u84"}}}}});